added pageOptions to the prePageCreateHook. Persistent context.
apify/browser-pool pull request #14
Opened 2021-02-02 21:03 UTC by petrpatek

The user data dir problem - `playwright` has a required `userDataDir` parameter that needs to provided in order to launch persistent context see https://playwright.dev/docs/1.7.0/api/class-browsertype#browsertypelaunchpersistentcontextuserdatadir-options. However `puppeteer` has this option in `launchOptions`. 

Possible solutions:
1) add `userDataDir` option to the `LaunchContext` and in the case of puppeteer merge it with the `launchOptions` option.
2) Create a default folder in the project root and use this.

2021-02-02 21:05 UTC, petrpatek commented
closes #12, #13

2021-02-03 13:16 UTC, mnmkng requested changes
I think we should reconsider the `usePersistentContext` and instead use `useIncognitoPages` which would be `false` by default for both Puppeteer and Playwright.

Mainly because it's really confusing to have separate defaults and it makes it hard to explain.

We would then also add `userDataDir` to the `launchContext` and set its default to `path.join(os.tmp(), 'some-random-hash')`.

2021-02-04 14:08 UTC, petrpatek commented on src/browser-pool.js
> + *  `pageId`: `string`, `browserController`: {@link BrowserController} and `pageOptions`: `object` -  library page creation options.
I would not add this logic to the BrowserPool. I think that we need to make clear how this works and why this works like that. I have written a little piece of something that should explain this.

2021-02-04 14:09 UTC, petrpatek commented on src/browser-controllers/playwright-controller.js
> +        const page = await this.browser.newPage(pageOptions);
There is no difference for us + we can easily make the options consistent.

2021-02-04 14:10 UTC, petrpatek commented on src/browser-pool.js
> +            pageOptions = {},
We won't be able to modify or add the options in the hooks then.

2021-02-04 14:10 UTC, petrpatek commented
This is the little thing I wrote to clarify the options situation.

Manipulating playwright context using `pageOptions` or `launchOptions`: Playwright allows customizing multiple browser attributes by browser context. You can customize some of them once the context is created, but some need to be customized within its creation. This part of the documentation should explain how you can effectively do customize the browser context.
First of all, let's take a look at what kind of context strategy you chose. You can choose between two strategies by `useIncognitoPages` `LaunchContext` option. If you set `useIncognitoPages` to `true`, you will create a new context within each new page, which allows you to handle each page its cookies and application data. This approach allows you to pass the context options as `pageOptions` because a new context is created once you create a new page. In this case, the `pageOptions` corresponds to these playwright options. https://playwright.dev/docs/api/class-browser#browsernewpageoptions
However, suppose you decided to keep `useIncognitoPages` false and create a shared context across all pages launched by one browser. In that case,  you should pass the `contextOptions` as a `launchOptions` since the context is created within the new browser launch. The `launchOptions` corresponds to these playwright options. https://playwright.dev/docs/api/class-browsertype#browsertypelaunchpersistentcontextuserdatadir-options. As you can see, these options contain not only ordinary playwright launch options but also the context options.

2021-02-04 15:11 UTC, mnmkng commented on src/abstract-classes/browser-plugin.js
> +     *  If set to true each page uses its own context that is destroyed once the page is closed or crashes.
I would say "by default" instead "if set to false". Also `pages use share` does not make sense. Either pages use, or pages share

2021-02-04 19:44 UTC, mnmkng approved these changes
I added one nitpick, but it's not really that important. I just remembered us talking about ternaries on the call 😄

2021-02-04 19:44 UTC, mnmkng commented on src/browser-pool.js
> +        }
I think this is where a ternary would be more explicit.

```js
const finalPageOptions = browserController.supportsPageOptions 
     ? pageOptions
     : undefined;
```

2021-02-04 19:44 UTC, merged