feat: make all the utils TS
apify/browser-pool pull request #31
Opened 2021-04-28 09:35 UTC by vladfrangu

Will depend on https://github.com/apify/apify-shared-js/issues/131

CC: @pocesar @B4nan @mnmkng

2021-04-28 14:30 UTC, pocesar commented
@vladfrangu there's #24 most of it is done

2021-04-28 14:36 UTC, vladfrangu commented
yeah, I'm planning to for the bigger classes since I saw you did a *lot* with generics, unless you meant something else! 😋

2021-05-31 17:11 UTC, mnmkng commented
@B4nan could you please check this?

@vladfrangu sorry for the long delay, https://github.com/apify/apify-shared-js/issues/131 is closed now and the shared repo is fully in TS, you can continue with the work.

2021-05-31 17:15 UTC, B4nan approved these changes
Other than the logger issue it looks fine

2021-08-03 08:01 UTC, B4nan requested changes
nit pick

2021-08-03 08:01 UTC, B4nan commented on src/logger.ts
> +import defaultLog from "@apify/log";
single quotes

2021-08-03 08:01 UTC, B4nan commented on src/logger.ts
> +    prefix: "BrowserPool",
single quotes

2021-08-03 08:13 UTC, vladfrangu commented
@B4nan Should I disable the `import/extensions` rule globally? It's not needed at all in JS/TS, and from one of your commits you even removed the extension from some imports 👀

2021-08-03 08:17 UTC, B4nan commented
afaik in TS we should not use extensions in imports, or something changed? :] i know they are required to use ESM, but we are not at that boat just yet and i expect TS to handle that for us anyway 

but i dont get the context, do we have some extensions in imports in the repo?

2021-08-03 08:19 UTC, vladfrangu commented
> but i dont get the context, do we have some extensions in imports in the repo?

![image](https://user-images.githubusercontent.com/17960496/127982540-1dcf8acc-ecce-48ba-bf4a-136b4a2d9b42.png)

2021-08-03 08:31 UTC, vladfrangu commented
Alrighty! Then this PR is review-and-merge ready 👍

2021-08-03 08:48 UTC, B4nan approved these changes

2021-08-03 08:53 UTC, B4nan commented
Looking at that commit I made and the linter passed just fine on that, weird. Maybe we should really disable that rule, personally I am not a big fan of airbnb style guide anyway :D 

Or fix it now in the JS files, but the extensions should not be there once its TS.

2021-08-03 09:01 UTC, vladfrangu commented
Scratch that, turns out the errors are caused by the fact the files are now `.ts` instead of `.js`, which the rule dislikes... 🙃 
And we cannot import .ts files, since they don't exist at runtime... Should I just disable the rule for now in the module instead?

2021-08-03 09:10 UTC, B4nan commented
yeah just add ignore comments i guess, we can deal with that later.

2021-08-03 09:19 UTC, merged